# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\Nguyen Phu Khuong\Desktop\Tools Login FB\ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1140, 500)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tableAccount = QtWidgets.QTableWidget(self.centralwidget)
        self.tableAccount.setGeometry(QtCore.QRect(10, 10, 1121, 321))
        self.tableAccount.setObjectName("tableAccount")
        self.tableAccount.setColumnCount(8)
        self.tableAccount.setRowCount(1)
        item = QtWidgets.QTableWidgetItem()
        self.tableAccount.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableAccount.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableAccount.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableAccount.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableAccount.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableAccount.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableAccount.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableAccount.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableAccount.setHorizontalHeaderItem(7, item)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1140, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "NGUYỄN PHÚ KHƯƠNG"))
        item = self.tableAccount.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "1"))
        item = self.tableAccount.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "UID"))
        item = self.tableAccount.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "PASSWORD"))
        item = self.tableAccount.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "2FA"))
        item = self.tableAccount.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "COOKIE"))
        item = self.tableAccount.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "NAME"))
        item = self.tableAccount.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "TOKEN"))
        item = self.tableAccount.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "TIẾN TRÌNH"))
